## Loan Status Prediction Project

### Project Overview

          This Project Predicts the loan status of a customer using Machine Learning. The model classifies whether a loan will be  **Approved or Not Approved** based on customer details.

### Libraries Used

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Preprocessing steps

In [41]:
data=pd.read_csv(r"C:\Users\ELCOT\Downloads\loan_approval_dataset.csv")

In [42]:
data.head(5)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [43]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1   no_of_dependents           4269 non-null   int64
 2    education                 4269 non-null   str
 3    self_employed             4269 non-null   str
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   str
dtypes: int64(10), str(3)
memory usage: 433.7 KB

### Remove Unneccessary column

In [44]:
data.drop(columns=['loan_id'],inplace=True)

In [45]:
data.columns

Index(['no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='str')

In [46]:
data.columns=data.columns.str.strip()

In [47]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='str')

In [48]:
data['Assets']=data.residential_assets_value+data.commercial_assets_value+data.luxury_assets_value+data.bank_asset_value

In [49]:
data.head(10)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,55000000
5,0,Graduate,Yes,4800000,13500000,10,319,6800000,8300000,13700000,5100000,Rejected,33900000
6,5,Graduate,No,8700000,33000000,4,678,22500000,14800000,29200000,4300000,Approved,70800000
7,2,Graduate,Yes,5700000,15000000,20,382,13200000,5700000,11800000,6000000,Rejected,36700000
8,0,Graduate,Yes,800000,2200000,20,782,1300000,800000,2800000,600000,Approved,5500000
9,5,Not Graduate,No,1100000,4300000,10,388,3200000,1400000,3300000,1600000,Rejected,9500000

In [50]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status', 'Assets'],
      dtype='str')

In [51]:
data.drop(columns=['residential_assets_value','commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'],inplace=True)

In [52]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000

In [53]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   no_of_dependents  4269 non-null   int64
 1   education         4269 non-null   str
 2   self_employed     4269 non-null   str
 3   income_annum      4269 non-null   int64
 4   loan_amount       4269 non-null   int64
 5   loan_term         4269 non-null   int64
 6   cibil_score       4269 non-null   int64
 7   loan_status       4269 non-null   str
 8   Assets            4269 non-null   int64
dtypes: int64(6), str(3)
memory usage: 300.3 KB

In [54]:
data.isnull().sum()

no_of_dependents    0
education           0
self_employed       0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
Assets              0
dtype: int64

In [55]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000

In [56]:
data.loan_status.unique()

<StringArray>
[' Approved', ' Rejected']
Length: 2, dtype: str

### Replacing all categorical column to numerical column

In [57]:
data['education']=data['education'].replace({' Graduate':1,' Not Graduate':0})
data['self_employed']=data['self_employed'].replace({' No':0,' Yes':1})
data['loan_status']=data['loan_status'].replace({' Approved':1,' Rejected':0})

In [58]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,1,50700000
1,0,0,1,4100000,12200000,8,417,0,17000000
2,3,1,0,9100000,29700000,20,506,0,57700000
3,3,1,0,8200000,30700000,8,467,0,52700000
4,5,0,1,9800000,24200000,20,382,0,55000000

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X=data.drop(columns=['loan_status']).astype(int)
y=data['loan_status'].astype(int)

In [61]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   no_of_dependents  4269 non-null   int64
 1   education         4269 non-null   int64
 2   self_employed     4269 non-null   int64
 3   income_annum      4269 non-null   int64
 4   loan_amount       4269 non-null   int64
 5   loan_term         4269 non-null   int64
 6   cibil_score       4269 non-null   int64
 7   Assets            4269 non-null   int64
dtypes: int64(8)
memory usage: 266.9 KB

In [62]:
y

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [63]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=43)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3415, 8), (854, 8), (3415,), (854,))

In [64]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.fit_transform(X_test)

## Machine Learning Models Used

In [65]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train_scaled,y_train)

LogisticRegression()

## Model Evaluation

In [66]:
model.score(x_test_scaled,y_test)

0.9297423887587822

In [67]:
pred_data=pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents', 'education', 'self_employed', 'income_annum','loan_amount', 'loan_term', 'cibil_score','Assets'])

In [68]:
pred_data=scaler.transform(pred_data)

In [69]:
model.predict(pred_data)

array([1])

## Conclusion:

### -> This model helps banks or financial institutions to decide whether a loan should be approved based on customer data.
### ->CIBIL Score: Highest impact; scores above 700 (e.g., 778 in approved samples) strongly favor approval, while low scores (e.g., 417) lead to rejection.
### ->Income & Assets: Annual income over 9M and total assets >50M correlate with approvals; low values signal risk.
### ->Dependents & Employment: More dependents or self-employment slightly hurt odds, but less than credit factors.

##